version: '2'

services:
  lint:
    image: buildkite/plugin-linter
    command: ['--id', 'tapendium/1password']
    volumes:
      - '.:/plugin:ro'

  tests:
    image: buildkite/plugin-tester
    volumes:
      - ".:/plugin:ro"


