version: '2'

services:
  lint:
    image: buildkite/plugin-linter:latest
    command: ['--id', 'tapendium/1password-secrets']
    volumes:
      - '.:/plugin:ro'

  tests:
    image: buildkite/plugin-tester:v4.0.0
    volumes:
      - ".:/plugin:ro"
