name: 1Password
description: Read secrets from 1Password
author: https://tapendium.com
requirements:
  - op
configuration:
  properties:
    debug:
      type: string
      description: Enable debug mode
    connect_host:
      type: string
      description: 1Password Connect Server host
    connect_token:
      type: string
      description: SecretsManager Secret ARN for 1Password Connect Server API token
    bin:
      type: string
      description: Name of 1Password CLI executable
    clear_token:
      type: boolean
      description: Clear OP_CONNECT_TOKEN environment variable on completion
    env:
      type: object
      patternProperties:
        ^[A-Z_]+$:
          type: string
          additionalProperties: false
    file:
      type: array
      items:
        type: object
        properties:
          path:
            type: string
            description: Path to config file with secret references
          out:
            type: string
            description: Path of file to write injected template to
        additionalProperties: false
  additionalProperties: false
