#!/usr/bin/expect
# shellcheck disable=SC1071

# Generate a valid 1Password session token
# Expects the following environment variables to be set:
# OP_ACCOUNT_URL URL used to sign in account
# OP_EMAIL       Email address of user to sign in
# OP_SECRET_KEY  Secret Key for user. Can be found in 1Password preferences
# OP_PASSWORD    User password

set timeout 20

log_user 0
spawn op signin --raw $::env(OP_ACCOUNT_URL) $::env(OP_EMAIL)
expect -re "Enter the Secret Key for $::env(OP_EMAIL) at $::env(OP_ACCOUNT_URL): " { send "$::env(OP_SECRET_KEY)\r" }
expect -re "Enter the password*" { send "$::env(OP_PASSWORD)\r" }
expect {
    -re "\n(.*)\r\n" {set result $expect_out(1,string)}
}
expect *
log_user 1
puts $result
